# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Università di Pisa @ GitHub #Organization
email: guido.scatena@unipi.it #TODO: email dedicata amministratore (admin-unipisa)
description: 
  Official GitHub Organization of Università di Pisa unipi.it
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

#Serverless URLS
#add_repo: "https://qz7961lmqi.execute-api.us-east-1.amazonaws.com/prod/add_repo"
#contact_us: "https://qz7961lmqi.execute-api.us-east-1.amazonaws.com/prod/contact_us"
#featured_repo: "https://qz7961lmqi.execute-api.us-east-1.amazonaws.com/prod/feature_repo"
#send_conf_email: "https://vq6t7mxduh.execute-api.us-east-1.amazonaws.com/production/sendConfirmationEmail"

# Build settings
markdown: kramdown
theme: jekyll-materialdocs
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md

#Enable auto-regeneration of the site when files are modified.
regenerate: true

#Incremental build only re-builds posts and pages that have changed, 
#resulting in significant performance improvements for large sites, 
#but may also break site generation in certain cases.
incremental: true

repository: "Unipisa/unipisa.github.io"

github: [metadata]
